apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bigquery-controller
  labels:
    name: bigquery-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: bigquery-controller
    spec:
      containers:
      - name: bigquery
        image: lisptick/pubsub_pipeline
        command : ["python", "controller.py"]
        args: ["pubsub-to-bigquery"]
        envFrom:
          - configMapRef:
              name: tw-conf
