apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: lisptick/pubsub_pipeline
        command : ["python", "controller.py"]
        args: ["twitter-to-pubsub"]
        envFrom:
          - configMapRef:
              name: tw-conf
          - secretRef:
              name: tw-sec
